/**
 * Created by zhubg on 2017/9/28.
 */

'use strict';

import {
  SINUP_GQL,
  SININ_GQL,
  SETACCOUNT_GQL,
  GETACCOUNT_GQL
} from './user_gql';
import {CALLAI_GQL, GETAILIST_GQL} from './callAI_gql';
import {TRANSFER_GQL, CLOSECHANNEL_GQL, GETPRICE_GQL} from './bill_gql';

module.exports = {
  SINUP_GQL:SINUP_GQL,
  CALLAI_GQL:CALLAI_GQL,
  SININ_GQL:SININ_GQL,
  SETACCOUNT_GQL:SETACCOUNT_GQL,
  GETACCOUNT_GQL:GETACCOUNT_GQL,
  GETAILIST_GQL:GETAILIST_GQL,
  TRANSFER_GQL:TRANSFER_GQL,
  CLOSECHANNEL_GQL:CLOSECHANNEL_GQL,
  GETPRICE_GQL:GETPRICE_GQL
};